### ISSUE TITLE
LSP

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#434]
This epic describes the efforts required to develop and improve RAML Language Server and its clients, including API Workbench branch.

# Recently done
## Features

Each feature assumes that it will be implemented in RAML server and supported BOTH  in API Workbench client and Visual Studio Code client.

- [x] [Create an initial version of the server part](https://github.com/mulesoft/api-workbench/issues/382)
- [x] Add validation to server
- [x] [Make a version of API workbench relying on LSP-only](https://github.com/mulesoft/api-workbench/issues/413)
- [x] [Add outline structure build to the server part](https://github.com/mulesoft/api-workbench/issues/383)
- [x] [Add suggestions support to the server](https://github.com/mulesoft/api-workbench/issues/407)
- [x] [Support open definition in RAML language server and clients](https://github.com/mulesoft/api-workbench/issues/423)
- [x] [Support find references in RAML language server and clients](https://github.com/mulesoft/api-workbench/issues/424)

# Next steps

## Features
- [ ] [Support rename in RAML language server and clients](https://github.com/mulesoft/api-workbench/issues/425)
- [ ] [Support mark occurrences in RAML language server and clients](https://github.com/mulesoft/api-workbench/issues/426)
- [ ] [Support web workers in language server](https://github.com/mulesoft/api-workbench/issues/409)

## CI & QA
- [x] [Perform an initial round of testing and bugfixing for RAML language server and clients](https://github.com/mulesoft/api-workbench/issues/427)
- [ ] [Port outline module tests to RAML language server CI](https://github.com/mulesoft/api-workbench/issues/428)
- [ ] [Port suggestions module tests to RAML server CI](https://github.com/mulesoft/api-workbench/issues/429)
- [ ] [Port a number of validation tests to RAML server CI](https://github.com/mulesoft/api-workbench/issues/430)
- [ ] [Create longevity CI mechanism for RAML server](https://github.com/mulesoft/api-workbench/issues/431)
- [ ] [Create longevity CI toolkit for API Workbench client](https://github.com/mulesoft/api-workbench/issues/432)
- [ ] [https://github.com/mulesoft/api-workbench/issues/new](https://github.com/mulesoft/api-workbench/issues/433)
